name: Werewolf
version: '${project.version}'
main: at.ingameengine.werewolf.Werewolf
api-version: 1.19
authors: [ Minegt, NoRepeat ]
commands:
  help:
    description: Shows the help page
    usage: /help
    aliases: [ h ]